<?php

namespace Modules\DeliveryMan\Providers;

use Illuminate\Foundation\Support\Providers\EventServiceProvider as ServiceProvider;
use Modules\DeliveryMan\Events\AssignDeliveryManEmail;
use Modules\DeliveryMan\Listeners\AssignDeliveryManEmailListener;
use Modules\DeliveryMan\Listeners\AssignDeliveryManPushNotificationListener;

class EventServiceProvider extends ServiceProvider
{
    protected $listen = [
        AssignDeliveryManEmail::class => [
            AssignDeliveryManEmailListener::class,
            AssignDeliveryManPushNotificationListener::class
        ]
    ];

    public function boot()
    {
        parent::boot(); //  Change the autogenerated stub
    }
}